### ISSUE TITLE
Running models takes hours

### ISSUE THREAD

**Issue by craine** [walkwithfastai/walkwithfastai.github.io#19]
Since the issue yesterday and today, my models just running resnet50 on an image set is taking 4 hours an epoch. It used to take about 4 minutes. I'm running GPU and higher RAM on colabs. I've verified GPU is running. Is something up?

**Comment by muellerzr** [comment]
I can't do much without a reproducer, please provide one.

**Comment by craine** [comment]
https://colab.research.google.com/drive/1OAftYeIC8iInzSCwYfuZEx9z83hZXomq?usp=sharing

**Comment by muellerzr** [comment]
Try moving your data out of Google Drive. For the last few months google drive has throttled access to data on it, so it can definitely slow down your training time as a result.

**Comment by craine** [comment]
I'll test out vanilla fastai to see if it is still the same.. that be helpful? I've used this setup for almost a year and this is the first time I've ever seen this.

**Comment by muellerzr** [comment]
That would indeed be helpful.

**Comment by craine** [comment]
Appears to be the same with vanilla.

**Comment by muellerzr** [comment]
Yeah, that's not a fastai (or wwf) issue, just google and their security. Not sure why some folks it takes quite a bit for this throttle to happen

**Comment by craine** [comment]
Just curious.. what do you use for your setup? Kaggle throttles my GPU too.. so it's a huge pain all the way around.

**Comment by muellerzr** [comment]
Local when I can, or colab. If I'm using something that has a large amount of data in the drive, I bring it to `/content` if possible

**Comment by muellerzr** [comment]
In your case though, since most kaggle competitions have hundreds of gigs of data, I train on the Kaggle GPU's when I don't on local
