### ISSUE TITLE
[FEATURE] Add mmdetection

### ISSUE THREAD

**Issue by dreamflasher** [walkwithfastai/walkwithfastai.github.io#21]
It would be awesome if you integrate https://github.com/open-mmlab/mmdetection – they have a huge amount of object detection models and it would be amazing to be able to use them with fastai. 

Does this make sense and how hard do you think it would be? (thinking about if I could contribute)

**Comment by muellerzr** [comment]
That would not be in line with this. The IceVision library is already
planning to integrate, and they are also going to be working on an
IceVision notebook I’ll be hosting here

**Comment by dreamflasher** [comment]
Exciting! Thanks for pointing me towards IceVision!
