### ISSUE TITLE
Lesson 5 - EfficientNet and Custom Pretrained Models errors on Google Colab

### ISSUE THREAD

**Issue by ne1s0n** [walkwithfastai/walkwithfastai.github.io#32]
I went to [https://walkwithfastai.com/EfficientNet_and_Custom_Weights](https://walkwithfastai.com/EfficientNet_and_Custom_Weights) and clicked on "Open in Colab" button. In Colab I set up hardware acceleration to GPU and started executing the cells.

The notebook runs as expected up to the instruction:

`body = create_timm_body('efficientnet_b3a', pretrained=True)`

which generates the error:

`NameError: name '_update_first_layer' is not defined`

It's probably an issue of versions. In the website it shows:

- fastai: 2.1.10
- fastcore: 1.3.13 
- wwf: 0.0.7
- timm: 0.3.2

but on Colab it gets:

- fastai : 2.3.1
- fastcore : 1.3.20
- wwf : 0.0.14
- timm : 0.4.5

Probably the newer fastai version masks the `_update_first_layer` function. In fact adding a cell with [the function definition pasted from here](https://github.com/fastai/fastai/blob/master/fastai/vision/learner.py#L48) allows the notebook to run as expected.

**Comment by muellerzr** [comment]
Thanks @ne1s0n! I've adjusted it.
