### ISSUE TITLE
Fastai wwf,timm trained (exported)model, loading in sagemaker endpoint error

### ISSUE THREAD

**Issue by m-ali-awan** [walkwithfastai/walkwithfastai.github.io#37]
I am trying to deploy fastai trained model (build using wwf(walk with fastai), and time), to sagemaker endpoint.
I have also included in required libraries as requirements.txt.
But the model is not being able to loaded by load_learner:

This is my model-fn
```
![Screenshot 2021-05-26 160613](https://user-images.githubusercontent.com/62832721/119653690-7ba81580-bddc-11eb-84be-fa6757e9825b.png)

# loads the model into memory from disk and returns it
def model_fn(model_dir):
  logger.info('model_fn')
  path_model = Path(model_dir)
  logger.debug(f'Loading model from path: {str(path_model/EXPORT_MODEL_NAME)}')
  print(path_model/EXPORT_MODEL_NAME)
  defaults.device = torch.device('cpu')
  print("Trying to Load Model::::")
  learn = load_learner(path_model/EXPORT_MODEL_NAME, cpu=True)
  print('MODEL-LOADED')
  logger.info('model loaded successfully')
  return learn
```
So, in the screenshot it can be seen that "MODEL-LOADED" is not printed.
Comparing, for a simple fastai-trained model, as a demo, that is working.

So kindly help me with this.

Thanks alot.

**Comment by muellerzr** [comment]
This is unrelated to the course, as I do not cover Sagemaker deployment.

**Comment by m-ali-awan** [comment]
Hi muellerzr, thanks for reply.
But please, give me some direction, as I am stuck with this.
