### ISSUE TITLE
Bug in wwf.utils.state_version

### ISSUE THREAD

**Issue by MarkB2** [walkwithfastai/walkwithfastai.github.io#4]
It uses now deprecated `pkg_resources` package (see https://github.com/googleapis/python-api-core/issues/27). It should use `importlib.metadata` (https://docs.python.org/3/library/importlib.metadata.html#distribution-versions) backported as `importlib_metadata` for Python < 3.7 (Colab uses 3.6.9).

For example running on Colab `03_tab.ae.ipynb` installs `wwt` package which requires fastai 2 (and install 2.0.16) but state_version reports 1.0.61. 

Running on Colab, `03_tab.stats.ipynb` executing `state_versions(['fastai', 'fastcore', 'wwf'])` throws 
`ContextualVersionConflict: (fastai 1.0.61 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('fastai>=2.0.0'), {'wwf'})` for the same reason.

**Comment by muellerzr** [comment]
@MarkB2 that may not be the case as to why that bug shows up. I have that happen and generally restarting my session once fastai is upgraded fixes the issue. Not sure about `pkg_resources` though, I will look into that.

**Comment by muellerzr** [comment]
Embarrassed it took me up until now to realize what this means, thanks Mark!
